In [1]:
import pandas as pd

propiedades_full=pd.read_csv("../Propiedades/properati-AR-2017-08-01-properties-sell-six_months.csv")

In [2]:
properties_by_type=propiedades_full[['place_name','property_type']]

In [3]:
properties_by_type_and_total=properties_by_type.groupby('place_name').count().reset_index()

In [4]:
properties_by_type_and_total.columns=['place_name','total_properties']
properties_by_type_and_total

                              place_name  total_properties
0                 Country Maschwitz Club                 3
1                             los alamos                 1
2                             9 de Abril                 3
3                                 Abasto               139
4                    Abril Club de Campo                19
5                        Acacias Blancas                34
6                               Acassuso               242
7                                Achiras                 8
8                          Adolfo Alsina                 8
9                                Adrogué               734
10       Aeropuerto Internacional Ezeiza                 2
11                             Agronomía                41
12                           Agua Blanca                 1
13                           Agua de Oro                 6
14                          Aguas Verdes                15
15              Albanueva Barrio Cerrado                26
16                       Aldea Brasilera                 1
17                           Aldea Salto                 1
18                            Aldo Bonzi                 6
19                        Alejandro Korn                16
20                        Alejandro Roca                 1
21                                  Alem                 2
22                                 Alfar                 1
23                            Almafuerte                 7
24                               Almagro              1165
25                       Almirante Brown                42
26                           Alta Gracia                18
27                              Altamira                14
28                     Alto Los Cardales                 3
29                     Altos de Hudson I                 1
...                                  ...               ...
1030           Villa Santa Cruz del Lago                11
1031                    Villa Santa Rita                57
1032                     Villa Sarmiento               152
1033                       Villa Soldati                15
1034                         Villa Tesei                15
1035                       Villa Udaondo                25
1036                         Villa Unión                 1
1037                       Villa Urquiza              1632
1038                      Villa Vatteone                 6
1039                       Villa Ventana                 1
1040                  Villa de Las Rosas                 4
1041                       Villa de Mayo                36
1042                       Villa de Soto                 2
1043                     Villa del Dique                23
1044                    Villa del Parque               488
1045                   Villa del Totoral                 8
1046  Village Golf & Tennis Country Club                 7
1047                             Villars                 1
1048                    Virasoro Village                 1
1049                     Virrey del Pino                16
1050                            Virreyes                41
1051                            Vistalba                 1
1052                 Wenceslao Escalante                 1
1053                               Wilde               139
1054                      William Morris                 1
1055                         Yerba Buena               191
1056                              Zelaya                 7
1057                              Zárate                15
1058               coordenadas 34.255511                 1
1059                             Álvarez                 1

[1060 rows x 2 columns]

In [5]:
properties_by_type=properties_by_type.groupby('place_name').apply(lambda x: x['property_type'].value_counts()).reset_index()
properties_by_type=pd.pivot_table(properties_by_type,index=['place_name'],columns=['level_1']).reset_index()
properties_by_type

                                 place_name property_type                   \
level_1                                                PH apartment  house
0                    Country Maschwitz Club           NaN       NaN    3.0
1                                los alamos           NaN       1.0    NaN
2                                9 de Abril           NaN       NaN    1.0
3                                    Abasto          14.0      79.0   37.0
4                       Abril Club de Campo           NaN       NaN   19.0
5                           Acacias Blancas           NaN       NaN   34.0
6                                  Acassuso           8.0      88.0  138.0
7                                   Achiras           NaN       4.0    3.0
8                             Adolfo Alsina           NaN       NaN    8.0
9                                   Adrogué          25.0     172.0  503.0
10          Aeropuerto Internacional Ezeiza           NaN       NaN    2.0
11                                Agronomía           7.0      29.0    4.0
12                              Agua Blanca           NaN       NaN    1.0
13                              Agua de Oro           NaN       NaN    6.0
14                             Aguas Verdes           2.0       8.0    5.0
15                 Albanueva Barrio Cerrado           NaN      15.0   11.0
16                          Aldea Brasilera           NaN       NaN    1.0
17                              Aldea Salto           NaN       NaN    1.0
18                               Aldo Bonzi           NaN       NaN    5.0
19                           Alejandro Korn           NaN       1.0   14.0
20                           Alejandro Roca           NaN       NaN    1.0
21                                     Alem           NaN       2.0    NaN
22                                    Alfar           NaN       NaN    1.0
23                               Almafuerte           NaN       NaN    7.0
24                                  Almagro          68.0    1023.0   38.0
25                          Almirante Brown           2.0      13.0   26.0
26                              Alta Gracia           NaN       3.0   15.0
27                                 Altamira           NaN       NaN   14.0
28                        Alto Los Cardales           NaN       NaN    3.0
29                        Altos de Hudson I           NaN       NaN    1.0
...                                     ...           ...       ...    ...
1030              Villa Santa Cruz del Lago           NaN       1.0   10.0
1031                       Villa Santa Rita          13.0      32.0   11.0
1032                        Villa Sarmiento          20.0      78.0   53.0
1033                          Villa Soldati           2.0       8.0    3.0
1034                            Villa Tesei           NaN       2.0   12.0
1035                          Villa Udaondo           1.0       1.0   23.0
1036                            Villa Unión           NaN       1.0    NaN
1037                          Villa Urquiza          92.0    1451.0   65.0
1038                         Villa Vatteone           1.0       1.0    4.0
1039                          Villa Ventana           NaN       NaN    1.0
1040                     Villa de Las Rosas           NaN       NaN    4.0
1041                          Villa de Mayo           NaN      10.0   25.0
1042                          Villa de Soto           NaN       NaN    2.0
1043                        Villa del Dique           NaN       NaN   23.0
1044                       Villa del Parque          47.0     378.0   50.0
1045                      Villa del Totoral           NaN       NaN    8.0
1046     Village Golf & Tennis Country Club           NaN       NaN    7.0
1047                                Villars           NaN       NaN    1.0
1048                       Virasoro Village           NaN       NaN    1.0
1049                        Virrey del Pino           NaN       1.0   15.0
1050                               Virreyes          12.0      10.0   16.0
1051                               Vistalba           NaN       NaN    1.0
1052                    Wenceslao Escalante           NaN       NaN    1.0
1053                                  Wilde          11.0      89.0   34.0
1054                         William Morris           NaN       NaN    1.0
1055                            Yerba Buena           NaN      79.0  103.0
1056                                 Zelaya           NaN       NaN    7.0
1057                                 Zárate           NaN       NaN   15.0
1058                  coordenadas 34.255511           NaN       NaN    1.0
1059                                Álvarez           NaN       NaN    1.0


level_1 store
0         NaN
1         NaN
2         2.0
3         9.0
4         NaN
5         NaN
6         8.0
7         1.0
8         NaN
9        34.0
10        NaN
11        1.0
12        NaN
13        NaN
14        NaN
15        NaN
16        NaN
17        NaN
18        1.0
19        1.0
20        NaN
21        NaN
22        NaN
23        NaN
24       36.0
25        1.0
26        NaN
27        NaN
28        NaN
29        NaN
...       ...
1030      NaN
1031      1.0
1032      1.0
1033      2.0
1034      1.0
1035      NaN
1036      NaN
1037     24.0
1038      NaN
1039      NaN
1040      NaN
1041      1.0
1042      NaN
1043      NaN
1044     13.0
1045      NaN
1046      NaN
1047      NaN
1048      NaN
1049      NaN
1050      3.0
1051      NaN
1052      NaN
1053      5.0
1054      NaN
1055      9.0
1056      NaN
1057      NaN
1058      NaN
1059      NaN

[1060 rows x 5 columns]

In [6]:
 properties_by_type.columns=['place_name','PH','apartment','house','store']

In [8]:
properties_by_type_and_total=pd.merge(properties_by_type,properties_by_type_and_total,on = 'place_name', how='left')

In [16]:
properties_by_type_and_total_mean=properties_by_type_and_total

In [23]:
properties_by_type_and_total_mean=properties_by_type_and_total_mean.fillna(value=0)

In [24]:
properties_by_type_and_total_mean['apartment_mean']=properties_by_type_and_total_mean['apartment']/properties_by_type_and_total_mean['total_properties']
properties_by_type_and_total_mean['PH_mean']=properties_by_type_and_total_mean['PH']/properties_by_type_and_total_mean['total_properties']
properties_by_type_and_total_mean['house_mean']=properties_by_type_and_total_mean['house']/properties_by_type_and_total_mean['total_properties']
properties_by_type_and_total_mean['store_mean']=properties_by_type_and_total_mean['store']/properties_by_type_and_total_mean['total_properties']

In [25]:
properties_by_type_and_total_mean

,place_name,PH,apartment,house,store,total_properties,apartment_mean,PH_mean,house_mean,store_mean
0,Country Maschwitz Club,0.0,0.0,3.0,0.0,3,0.000000,0.000000,1.000000,0.000000
1,los alamos,0.0,1.0,0.0,0.0,1,1.000000,0.000000,0.000000,0.000000
2,9 de Abril,0.0,0.0,1.0,2.0,3,0.000000,0.000000,0.333333,0.666667
3,Abasto,14.0,79.0,37.0,9.0,139,0.568345,0.100719,0.266187,0.064748
4,Abril Club de Campo,0.0,0.0,19.0,0.0,19,0.000000,0.000000,1.000000,0.000000
5,Acacias Blancas,0.0,0.0,34.0,0.0,34,0.000000,0.000000,1.000000,0.000000
6,Acassuso,8.0,88.0,138.0,8.0,242,0.363636,0.033058,0.570248,0.033058
7,Achiras,0.0,4.0,3.0,1.0,8,0.500000,0.000000,0.375000,0.125000
8,Adolfo Alsina,0.0,0.0,8.0,0.0,8,0.000000,0.000000,1.000000,0.000000
9,Adrogué,25.0,172.0,503.0,34.0,734,0.234332,0.034060,0.685286,0.046322
10,Aeropuerto Internacional Ezeiza,0.0,0.0,2.0,0.0,2,0.000000,0.000000,1.000000,0.000000
11,Agronomía,7.0,29.0,4.0,1.0,41,0.707317,0.170732,0.097561,0.024390
12,Agua Blanca,0.0,0.0,1.0,0.0,1,0.000000,0.000000,1.000000,0.000000
13,Agua de Oro,0.0,0.0,6.0,0.0,6,0.000000,0.000000,1.000000,0.000000
14,Aguas Verdes,2.0,8.0,5.0,0.0,15,0.533333,0.133333,0.333333,0.000000
15,Albanueva Barrio Cerrado,0.0,15.0,11.0,0.0,26,0.576923,0.000000,0.423077,0.000000
16,Aldea Brasilera,0.0,0.0,1.0,0.0,1,0.000000,0.000000,1.000000,0.000000
17,Aldea Salto,0.0,0.0,1.0,0.0,1,0.000000,0.000000,1.000000,0.000000
18,Aldo Bonzi,0.0,0.0,5.0,1.0,6,0.000000,0.000000,0.833333,0.166667
19,Alejandro Korn,0.0,1.0,14.0,1.0,16,0.062500,0.000000,0.875000,0.062500
20,Alejandro Roca,0.0,0.0,1.0,0.0,1,0.000000,0.000000,1.000000,0.000000
21,Alem,0.0,2.0,0.0,0.0,2,1.000000,0.000000,0.000000,0.000000
22,Alfar,0.0,0.0,1.0,0.0,1,0.000000,0.000000,1.000000,0.000000
23,Almafuerte,0.0,0.0,7.0,0.0,7,0.000000,0.000000,1.000000,0.000000
24,Almagro,68.0,1023.0,38.0,36.0,1165,0.878112,0.058369,0.032618,0.030901
25,Almirante Brown,2.0,13.0,26.0,1.0,42,0.309524,0.047619,0.619048,0.023810
26,Alta Gracia,0.0,3.0,15.0,0.0,18,0.166667,0.000000,0.833333,0.000000
27,Altamira,0.0,0.0,14.0,0.0,14,0.000000,0.000000,1.000000,0.000000
28,Alto Los Cardales,0.0,0.0,3.0,0.0,3,0.000000,0.000000,1.000000,0.000000
29,Altos de Hudson I,0.0,0.0,1.0,0.0,1,0.000000,0.000000,1.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...
1030,Villa Santa Cruz del Lago,0.0,1.0,10.0,0.0,11,0.090909,0.000000,0.909091,0.000000
1031,Villa Santa Rita,13.0,32.0,11.0,1.0,57,0.561404,0.228070,0.192982,0.017544
1032,Villa Sarmiento,20.0,78.0,53.0,1.0,152,0.513158,0.131579,0.348684,0.006579
1033,Villa Soldati,2.0,8.0,3.0,2.0,15,0.533333,0.133333,0.200000,0.133333
1034,Villa Tesei,0.0,2.0,12.0,1.0,15,0.133333,0.000000,0.800000,0.066667
1035,Villa Udaondo,1.0,1.0,23.0,0.0,25,0.040000,0.040000,0.920000,0.000000
1036,Villa Unión,0.0,1.0,0.0,0.0,1,1.000000,0.000000,0.000000,0.000000
1037,Villa Urquiza,92.0,1451.0,65.0,24.0,1632,0.889093,0.056373,0.039828,0.014706
1038,Villa Vatteone,1.0,1.0,4.0,0.0,6,0.166667,0.166667,0.666667,0.000000
1039,Villa Ventana,0.0,0.0,1.0,0.0,1,0.000000,0.000000,1.000000,0.000000
1040,Villa de Las Rosas,0.0,0.0,4.0,0.0,4,0.000000,0.000000,1.000000,0.000000
1041,Villa de Mayo,0.0,10.0,25.0,1.0,36,0.277778,0.000000,0.694444,0.027778
1042,Villa de Soto,0.0,0.0,2.0,0.0,2,0.000000,0.000000,1.000000,0.000000
1043,Villa del Dique,0.0,0.0,23.0,0.0,23,0.000000,0.000000,1.000000,0.000000
1044,Villa del Parque,47.0,378.0,50.0,13.0,488,0.774590,0.096311,0.102459,0.026639
1045,Villa del Totoral,0.0,0.0,8.0,0.0,8,0.000000,0.000000,1.000000,0.000000
1046,Village Golf & Tennis Country Club,0.0,0.0,7.0,0.0,7,0.000000,0.000000,1.000000,0.000000
1047,Villars,0.0,0.0,1.0,0.0,1,0.000000,0.000000,1.000000,0.000000
1048,Virasoro Village,0.0,0.0,1.0,0.0,1,0.000000,0.000000,1.000000,0.000000
1049,Virrey del Pino,0.0,1.0,15.0,0.0,16,0.062500,0.000000,0.937500,0.000000
1050,Virreyes,12.0,10.0,16.0,3.0,41,0.243902,0.292683,0.390244,0.073171
1051,Vistalba,0.0,0.0,1.0,0.0,1,0.000000,0.000000,1.000000,0.000000
1052,Wenceslao Escalante,0.0,0.0,1.0,0.0,1,0.000000,0.000000,1.000000,0.000000
1053,Wilde,11.0,89.0,34.0,5.0,139,0.640288,0.079137,0.244604,0.035971
1054,William Morris,0.0,0.0,1.0,0.0,1,0.000000,0.000000,1.000000,0.000000
1055,Yerba Buena,0.0,79.0,103.0,9.0,191,0.413613,0.000000,0.539267,0.047120
1056,Zelaya,0.0,0.0,7.0,0.0,7,0.000000,0.000000,1.000000,0.000000
1057,Zárate,0.0,0.0,15.0,0.0,15,0.000000,0.000000,1.000000,0.000000
1058,coordenadas 34.255511,0.0,0.0,1.0,0.0,1,0.000000,0.000000,1.000000,0.000000
1059,Álvarez,0.0,0.0,1.0,0.0,1,0.000000,0.000000,1.000000,0.000000